# Generated by Django 6.0 on 2025-12-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(blank=True, help_text="Path under static/, e.g. 'images/items/emberwreath-longbow.png'", max_length=200),
        ),
    ]
